### ISSUE TITLE
The service "ivory.google_map.geocoder" has a dependency on a non-existent service "ivory.serializer"

### ISSUE THREAD

**Issue by ignas3run** [egeloen/IvoryGoogleMapBundle#203] opened 2017-02-20 15:56 UTC
I was using geococer successfully for the last few months, but few days ago I tried updating composer and I got this error:

>   - Installing egeloen/google-map-bundle (dev-master 1c0bb34)
>     Cloning 1c0bb34bf097cedd56623746de367c4094d852d4
>     Failed to download egeloen/google-map-bundle from source: Failed to clone https://github.com/egeloen/IvoryGoogleMapBundle.git, git was not found, check that it is installed and in your PATH env.
> 
> 'git' is not recognized as an internal or external command,
> operable program or batch file.
> 
>     Now trying to download from dist
>   - Installing egeloen/google-map-bundle (dev-master 1c0bb34)
>     Downloading: 100%

> [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
> The service "ivory.google_map.geocoder" has a dependency on a non-existent service "ivory.serializer".

Now my project is not working at all. I am using bundle version of `dev-master`:

My composer.json:

```
"require": {
        "egeloen/google-map": "^2.0@dev",
        "egeloen/google-map-bundle": "dev-master",
```

My config.yml:

```
httplug:
    classes:
        client: Http\Adapter\Guzzle6\Client
        message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
    clients:
        index:
            factory: httplug.factory.guzzle6
            config:
                 verify: false

ivory_google_map:
    api_key: "%google_maps_api_key%"
    geocoder:
        client: httplug.client.default
        message_factory: httplug.message_factory.default
```

**UPDATE**

I have read updated docs and updated my composer.json:

```
"egeloen/serializer": "^1.0@dev",
"egeloen/serializer-bundle": "dev-master",
```

Now I get error:

> The service "ivory.serializer.cache_warmer" has a dependency on a non-existent service "cache.system".

I checked serializer [packagist](https://packagist.org/packages/egeloen/serializer-bundle) where you stated all dependencies:

> requires (dev)
> 
> doctrine/annotations: ^1.0
> friendsofphp/php-cs-fixer: ^2.0
> symfony/phpunit-bridge: ^2.7|^3.0
> phpunit/phpunit: ^5.4
> symfony/cache: ^3.0
> friendsofsymfony/rest-bundle: ^2.0
> symfony/form: ^2.7|^3.0
> symfony/translation: ^2.7|^3.0

Does this mean I have to update my `composer.json require-dev` block with these packages?

What happened and how could I resolve this problem? Is there a log where you stated how to safelly update your bundle step by step?

**Comment by ignas3run** [comment] 2017-02-20 16:29
I googled service `cache.system` and it seems that is is only available for symfony 3.1 and I am using Symfony 2.8. Does that mean that your bundle is not available for older symfony versions or is there a configurations of serializer to disable `cache.system`?

**Comment by egeloen** [comment] 2017-02-20 19:22
@ignas3run Thanks a lot for your feedback! I just integrate the Ivory Serializer in this bundle few days ago and so, I'm happy to see you trying to use it already :)

If you get this error means you're using services (such as geocoder, directions, ...). The Ivory serializer is now used in order to deserialize google response instead of the previous hardcoded parser (very very limited)...

To install the serializer, you need:

``` bash
$ composer require egeloen/serializer
$ composer require egeloen/serializer-bundle
```

Since both these two libraries have not been released yet (will be when I release here), you need to rely on `dev-master` or `^1.0@dev` meanwhile.

Then, load the `IvorySerializerBundle` in your app kernel.

For the cache, if you're using Symfony >= 3.1, nothing to do, the bundle will automatically use the built-in `cache.system` cache pool from the Symfony framework. If you're using a lower versions of Symfony (< 3.1), then you need to create manually a PSR-6 cache pool service and use it in the serializer configuration:

Unfortunatelly for you, this is the only part of the doc I have not written yet: https://github.com/egeloen/IvorySerializerBundle/blob/master/Resources/doc/configuration/cache.md

First, install the Symfony cache component:

``` bash
$ composer require symfony/cache
```

Then, defined a service which will define a PSR-6 pool (such as FilesystemAdapter, ApcuAdapter, ...) according to your need. Given the pool cache service is named `acme.cache.pool`, then, configure the bundle with:

``` yaml
ivory_serializer:
    mapping:
        cache:
            pool: acme.cache.pool
```

Why I have to define a cache pool? When you're in production env, the bundle will parse metadata XML file in order to determine how to deserialize google response. If there is no cache, the metadata parsing is done everytime...

I hope it is now more clear for you (and others) :)

**Comment by egeloen** [comment] 2017-02-20 19:27
I know for now it is not perfect but I'm still thinking of a better way to handle this for Symfony < 3.1 since it does not support PSR-6 pool and rely on a "specific" way to handle caching...

**Comment by egeloen** [comment] 2017-02-20 21:07
I have discussed with @geoffrey-brier about the caching issue and egeloen/IvorySerializerBundle#5 should fix it.

Can you give it a try? by using:

```
"egeloen/serializer": "^1.0@dev"
"egeloen/serializer-bundle": "dev-cache"
```

**Comment by ignas3run** [comment] 2017-02-21 10:02
@egeloen thank you for your fast answer!

Thank you for explaining the use of serializer. Now I installed "symfony/cache" and "egeloen/serializer-bundle": "dev-cache" as you told and I am not getting any global error anymore, As I understand from [here](https://github.com/egeloen/IvorySerializerBundle/pull/5) `dev-cache` creates cache pool it self or am I wrong? 

> Automatically create a PSR-6 filesystem adapter using the kernel.cache_dir if the cache.system pool does not exist or no explicit cache service has been configured.

Now I get only error when using geocoder:

```
$geocoder = $this->get('ivory.google_map.geocoder');
$geoRequest = new GeocoderAddressRequest($object->getCity().', '.$object->getCountry()->getName());
/** @var GeocoderResponse $geoResponse */
$geoResponse = $geocoder->geocode($geoRequest); // this is the line that throws en error
```

Error:
> [ERROR 1845] Element 'serializer': No matching global declaration available for the validation root.

I double checked geocoder [docs ](https://github.com/egeloen/IvoryGoogleMapBundle/blob/master/Resources/doc/service/geocoder.md)and it looks like I use it as it is written there.

**P.S.**
Also if I misunderstood and `dev-cache` is not automativcally creating cache pool, I have no clue how to create one, since here cache pools are only [documented](http://symfony.com/doc/current/components/cache/cache_pools.html) in symfony 3 docs.

**Comment by ma2thieu** [comment] 2017-02-21 10:03
Thanks it works for me on SF2.8
```
        "egeloen/google-map": "^2.0@dev",
        "egeloen/google-map-bundle": "dev-master",
        "egeloen/serializer": "^1.0@dev",
        "egeloen/serializer-bundle": "dev-cache",
        "php-http/httplug-bundle": "^1.3",
        "php-http/guzzle6-adapter": "^1.1",
        "willdurand/geocoder": "2.*",
```

**Comment by ignas3run** [comment] 2017-02-21 10:08
@ma2thieu I think it is because you are not using current bundle geocoder, but `willdurand/geocoder` or am I mistaking?

**Comment by ma2thieu** [comment] 2017-02-21 10:16
@ignas3run I thought I was but actually I don't, this is my config : 
```
ivory_google_map:
    api_key: "%googlemap_api_key%"
    geocoder:
        client: httplug.client.default
        message_factory: httplug.message_factory.default
        api_key: "%googlemap_api_key%"
```

(I removed `"willdurand/geocoder": "2.*"` from my `composer.json`)

**Comment by ignas3run** [comment] 2017-02-21 10:25
@ma2thieu weird I have the same configurations. Could you share your geocoder action? That would help me, thank you.

**Comment by ma2thieu** [comment] 2017-02-21 10:32
@ignas3run sure, here it is : 
```
namespace wbx\AppBundle\Manager;

use Doctrine\ORM\EntityManager;
use Symfony\Component\Translation\TranslatorInterface;
use Ivory\GoogleMap\Service\Geocoder\GeocoderService;
use Http\Adapter\Guzzle6\Client;
use Http\Message\MessageFactory\GuzzleMessageFactory;
use Ivory\GoogleMap\Service\Geocoder\Request\GeocoderAddressRequest;

class GeocoderManager {
    protected $trans;

    public function __construct(TranslatorInterface $trans) {
        $this->trans = $trans;
    }

    public function geoCode($address) {
        $geocoder = new GeocoderService(new Client(), new GuzzleMessageFactory());
        $request = new GeocoderAddressRequest($address);
        $response = $geocoder->geocode($request);

        $status = $response->getStatus();
        if ($status != "OK") {
            return $this->trans->trans('gmap.' . $status);
        }
        else {
            $results = $response->getResults();
            return array(
                $results[0]->getGeometry()->getLocation()->getLatitude(),
                $results[0]->getGeometry()->getLocation()->getLongitude()
            );
        }
    }
}
```

**Comment by ignas3run** [comment] 2017-02-21 11:02
@egeloen I got it working, by calling `new GeocoderService()` instead of `$this->get('ivory.google_map.geocoder')` like @ma2thieu . I have no clue why I am getting error ([ERROR 1845] Element 'serializer': No matching global declaration available for the validation root.) while calling service even tho I am working in controller.

```
//            not working 
            $geocoder = $this->get('ivory.google_map.geocoder');
            $geoRequest = new GeocoderAddressRequest($object->getCity().', '.$object->getCountry()->getName());
            /** @var GeocoderResponse $geoResponse */
            $geoResponse = $geocoder->geocode($geoRequest); // falls here


//            this works
            $client = new Client([
                'verify' => false,
            ]);
            $adapter = new Adapter($client);
            $geocoder = new GeocoderService($adapter, new GuzzleMessageFactory());
            $geoRequest = new GeocoderAddressRequest($object->getCity().', '.$object->getCountry()->getName());
            /** @var GeocoderResponse $geoResponse */
            $geoResponse = $geocoder->geocode($geoRequest);
```

**Comment by egeloen** [comment] 2017-02-21 13:44
@ignas3run I need to give it a try in a real symfony project since your solution works but goes against performance since you use the serializer without caching. When you create you Geocoder service (`new GeocoderService`, you don't pass a Serializer so it creates one automatically without caching...

**Comment by egeloen** [comment] 2017-02-21 13:57
> As I understand from here dev-cache creates cache pool it self or am I wrong?

Yes, this branch will automatically creates a PSR-6 pool using a filesystem stratégy in the `kernel.cache_dir` of your application.

> Also, will dev-cache be replaced in the future for stable version too?

Yes, if it's working it is the plan. This PR will allow us to have a Symfony < 3.1 layer compat automatically while keeping the ability to define a custom cache pool in the config.

> [ERROR 1845] Element 'serializer': No matching global declaration available for the validation root.

For this error, I see where does it come from but I don't know how do you get such error. The error is related to https://github.com/egeloen/ivory-google-map/blob/master/src/Service/Serializer/Geocoder/GeocoderResponse.xml and other metadata files but I don't get why these files can't be parsed...

**Comment by egeloen** [comment] 2017-02-21 19:37
@ignas3run I have merged the referenced PR and also apply some other adjustments in order to have a full compat :) Give a look to the referenced commit or https://github.com/symfony/symfony-standard/compare/2.8...egeloen:google-map-bundle-issue-203 It is a simple commit where I enable the geocoder in Symfony 2.8

**Comment by ignas3run** [comment] 2017-02-22 09:58
Okay so I changed everything according to your [commit](https://github.com/symfony/symfony-standard/compare/2.8...egeloen:google-map-bundle-issue-203). Unfortunatelly, with your config.yml I am getting Guzzle error:

> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Now when I update your config with:

```
httplug:
    classes:
        client: Http\Adapter\Guzzle6\Client
        message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
    clients:
        index:
            factory: httplug.factory.guzzle6
            config:
                 verify: false
```
 I am now facing same error as before:

> [ERROR 1845] Element 'serializer': No matching global declaration available for the validation root.

Also, why are you not including `api_key` in config? For me bundle is not rendering maps without it.

Thank you for your time! :)

**Comment by egeloen** [comment] 2017-02-22 17:55
Hum @ignas3run Are you using a Windows system?

**Comment by egeloen** [comment] 2017-02-23 18:20
@ignas3run What is your OS, PHP version and PHP extensions loaded?

**Comment by ignas3run** [comment] 2017-02-24 08:29
@egeloen 
**OS**: Windows 10
**PHP**: Version 5.6.28
**Extensions** (from php.ini):
extension=php_bz2.dll
extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_mbstring.dll
extension=php_exif.dll
extension=php_mysql.dll
extension=php_mysqli.dll
extension=php_pdo_mysql.dll
extension=php_pdo_sqlite.dll
extension=php_soap.dll
extension=php_apcu.dll

**Comment by ignas3run** [comment] 2017-02-24 08:30
If using without serializer as I do now is not big of a problem, I can leave it as it is, untill there will be more people having same problem so you could resolve it with more input :)

**Comment by egeloen** [comment] 2017-02-24 10:20
@ignas3run I know where is the problem. It is related to PHP on Windows (I have never tested it on this platform). I'm currently playing with AppVeyor in order to set up a CI on my projects in order to be sure everything is working on Windows as well as on UNIX systems. Let me some time to debug and fix it now :)

**Comment by egeloen** [comment] 2017-02-25 21:54
@ignas3run Can you provide a strack trace of your error with the current versions of all depenencies (composer update)? I would like to know if it comes from the document loading [here](https://github.com/egeloen/ivory-serializer/blob/master/src/Mapping/Loader/XmlClassMetadataLoader.php#L184) or the documentation validation [here](https://github.com/egeloen/ivory-serializer/blob/master/src/Mapping/Loader/XmlClassMetadataLoader.php#L190).

The issue seems not related to windows since AppVeyor [build](https://ci.appveyor.com/project/egeloen/ivory-serializer/build/1.0.1) is green.

**Comment by ignas3run** [comment] 2017-02-27 11:04
**Sure, here is stack trace:**

> Stack Trace
> in vendor\egeloen\serializer\src\Mapping\Loader\XmlClassMetadataLoader.php at line 228   -
```
        $this->setLibXmlState($internalErrors, $disableEntities);
        return new \InvalidArgumentException(implode(PHP_EOL, $errors));
    }
    /**
```
> at XmlClassMetadataLoader ->createException ('C:\xampp\htdocs\trainingexperience_symfony\src\Application\Sonata\MediaBundle\Resources\config\serializer\Document.Gallery.xml', false, false) 
> in vendor\egeloen\serializer\src\Mapping\Loader\XmlClassMetadataLoader.php at line 190   + 
> at XmlClassMetadataLoader ->loadDocument ('C:\xampp\htdocs\trainingexperience_symfony\src\Application\Sonata\MediaBundle\Resources\config\serializer\Document.Gallery.xml') 
> in vendor\egeloen\serializer\src\Mapping\Loader\XmlClassMetadataLoader.php at line 25   + 
> at XmlClassMetadataLoader ->loadFile ('C:\xampp\htdocs\trainingexperience_symfony\src\Application\Sonata\MediaBundle\Resources\config\serializer\Document.Gallery.xml') 
> in vendor\egeloen\serializer\src\Mapping\Loader\AbstractFileClassMetadataLoader.php at line 75   + 
> at AbstractFileClassMetadataLoader ->loadData ('Ivory\GoogleMap\Service\Geocoder\Response\GeocoderResponse') 
> in vendor\egeloen\serializer\src\Mapping\Loader\AbstractClassMetadataLoader.php at line 70   + 
> at AbstractClassMetadataLoader ->loadClassMetadata (object(ClassMetadata)) 
> in vendor\egeloen\serializer\src\Mapping\Loader\FileClassMetadataLoader.php at line 65   + 
> at FileClassMetadataLoader ->loadClassMetadata (object(ClassMetadata)) 
> in vendor\egeloen\serializer\src\Mapping\Loader\ChainClassMetadataLoader.php at line 42   + 
> at ChainClassMetadataLoader ->loadClassMetadata (object(ClassMetadata)) 
> in vendor\egeloen\serializer\src\Mapping\Loader\DirectoryClassMetadataLoader.php at line 70   + 
> at DirectoryClassMetadataLoader ->loadClassMetadata (object(ClassMetadata)) 
> in vendor\egeloen\serializer\src\Mapping\Loader\ChainClassMetadataLoader.php at line 42   + 
> at ChainClassMetadataLoader ->loadClassMetadata (object(ClassMetadata)) 
> in vendor\egeloen\serializer\src\Mapping\Factory\ClassMetadataFactory.php at line 87   + 
> at ClassMetadataFactory ->fetchClassMetadata ('Ivory\GoogleMap\Service\Geocoder\Response\GeocoderResponse') 
> in vendor\egeloen\serializer\src\Mapping\Factory\AbstractClassMetadataFactory.php at line 33   + 
> at AbstractClassMetadataFactory ->getClassMetadata ('Ivory\GoogleMap\Service\Geocoder\Response\GeocoderResponse') 
> in vendor\egeloen\serializer\src\Type\ObjectType.php at line 42   + 
> at ObjectType ->convert (array('results' => array(array('address_components' => array(array('long_name' => 'Spain', 'short_name' => 'ES', 'types' => array('country', 'political'))), 'formatted_address' => 'Spain', 'geometry' => array('bounds' => array('northeast' => array('lat' => '43.8504', 'lng' => '4.6362'), 'southwest' => array('lat' => '27.4985', 'lng' => '-18.2648001')), 'location' => array('lat' => '40.463667', 'lng' => '-3.74922'), 'location_type' => 'APPROXIMATE', 'viewport' => array('northeast' => array('lat' => '45.244', 'lng' => '5.098'), 'southwest' => array('lat' => '35.173', 'lng' => '-12.524'))), 'place_id' => 'ChIJi7xhMnjjQgwR7KNoB5Qs7KY', 'types' => array('country', 'political'))), 'status' => 'OK'), object(TypeMetadata), object(Context)) 
> in vendor\egeloen\serializer\src\Navigator\Navigator.php at line 59   + 
> at Navigator ->navigate (array('results' => array(array('address_components' => array(array('long_name' => 'Spain', 'short_name' => 'ES', 'types' => array('country', 'political'))), 'formatted_address' => 'Spain', 'geometry' => array('bounds' => array('northeast' => array('lat' => '43.8504', 'lng' => '4.6362'), 'southwest' => array('lat' => '27.4985', 'lng' => '-18.2648001')), 'location' => array('lat' => '40.463667', 'lng' => '-3.74922'), 'location_type' => 'APPROXIMATE', 'viewport' => array('northeast' => array('lat' => '45.244', 'lng' => '5.098'), 'southwest' => array('lat' => '35.173', 'lng' => '-12.524'))), 'place_id' => 'ChIJi7xhMnjjQgwR7KNoB5Qs7KY', 'types' => array('country', 'political'))), 'status' => 'OK'), object(Context), object(TypeMetadata)) 
> in vendor\egeloen\serializer\src\Navigator\EventNavigator.php at line 81   + 
> at EventNavigator ->navigate (array('results' => array(array('address_components' => array(array('long_name' => 'Spain', 'short_name' => 'ES', 'types' => array('country', 'political'))), 'formatted_address' => 'Spain', 'geometry' => array('bounds' => array('northeast' => array('lat' => '43.8504', 'lng' => '4.6362'), 'southwest' => array('lat' => '27.4985', 'lng' => '-18.2648001')), 'location' => array('lat' => '40.463667', 'lng' => '-3.74922'), 'location_type' => 'APPROXIMATE', 'viewport' => array('northeast' => array('lat' => '45.244', 'lng' => '5.098'), 'southwest' => array('lat' => '35.173', 'lng' => '-12.524'))), 'place_id' => 'ChIJi7xhMnjjQgwR7KNoB5Qs7KY', 'types' => array('country', 'political'))), 'status' => 'OK'), object(Context), object(TypeMetadata)) 
> in vendor\egeloen\serializer\src\Serializer.php at line 107   + 
> at Serializer ->navigate ('{ "results" : [ { "address_components" : [ { "long_name" : "Spain", "short_name" : "ES", "types" : [ "country", "political" ] } ], "formatted_address" : "Spain", "geometry" : { "bounds" : { "northeast" : { "lat" : 43.8504, "lng" : 4.6362 }, "southwest" : { "lat" : 27.4985, "lng" : -18.2648001 } }, "location" : { "lat" : 40.46366700000001, "lng" : -3.74922 }, "location_type" : "APPROXIMATE", "viewport" : { "northeast" : { "lat" : 45.244, "lng" : 5.098 }, "southwest" : { "lat" : 35.17300000000001, "lng" : -12.524 } } }, "place_id" : "ChIJi7xhMnjjQgwR7KNoB5Qs7KY", "types" : [ "country", "political" ] } ], "status" : "OK" } ', '2', 'json', object(Context), object(TypeMetadata)) 
> in vendor\egeloen\serializer\src\Serializer.php at line 84   + 
> at Serializer ->deserialize ('{ "results" : [ { "address_components" : [ { "long_name" : "Spain", "short_name" : "ES", "types" : [ "country", "political" ] } ], "formatted_address" : "Spain", "geometry" : { "bounds" : { "northeast" : { "lat" : 43.8504, "lng" : 4.6362 }, "southwest" : { "lat" : 27.4985, "lng" : -18.2648001 } }, "location" : { "lat" : 40.46366700000001, "lng" : -3.74922 }, "location_type" : "APPROXIMATE", "viewport" : { "northeast" : { "lat" : 45.244, "lng" : 5.098 }, "southwest" : { "lat" : 35.17300000000001, "lng" : -12.524 } } }, "place_id" : "ChIJi7xhMnjjQgwR7KNoB5Qs7KY", "types" : [ "country", "political" ] } ], "status" : "OK" } ', 'Ivory\GoogleMap\Service\Geocoder\Response\GeocoderResponse', 'json', object(Context)) 
> in vendor\egeloen\google-map\src\Service\AbstractSerializableService.php at line 106   + 
> at AbstractSerializableService ->deserialize (object(Response), 'Ivory\GoogleMap\Service\Geocoder\Response\GeocoderResponse', object(Context)) 
> in vendor\egeloen\google-map\src\Service\Geocoder\GeocoderService.php at line 60   + 
> at GeocoderService ->geocode (object(GeocoderAddressRequest)) 
> in src\IndexBundle\Controller\AdminController.php at line 239   + 
> at AdminController ->verifyOfferAction ('7') 
> at call_user_func_array (array(object(AdminController), 'verifyOfferAction'), array('7')) 
> in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php at line 144   + 
> at HttpKernel ->handleRaw (object(Request), '1') 
> in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php at line 64   + 
> at HttpKernel ->handle (object(Request), '1', true) 
> in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel.php at line 69   + 
> at ContainerAwareHttpKernel ->handle (object(Request), '1', true) 
> in vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php at line 185   + 
> at Kernel ->handle (object(Request)) 
> in web\app_dev.php at line 30   + 

**Here is my composer.json:**

```
"require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "symfony/assetic-bundle": "^2.7",
        "symfony/translation": "^2.8",
        "hwi/oauth-bundle": "^0.4.2",
        "leafo/scssphp": "dev-master",
        "mopa/bootstrap-bundle": "dev-master",
        "twbs/bootstrap-sass": "3.3.*",
        "patchwork/jsqueeze": "^2.0",
        "knplabs/knp-menu-bundle": "^2.0",
        "knplabs/knp-paginator-bundle": "^2.5",
        "fortawesome/font-awesome": "~4.0",
        "sonata-project/admin-bundle": "^3.7",
        "sonata-project/doctrine-orm-admin-bundle": "^3.0",
        "sonata-project/media-bundle": "^3.3",
        "snilius/twig-sort-by-field": "^0.1.5",
        "egeloen/google-map": "^2.0@dev",
        "egeloen/google-map-bundle": "^3.0@dev",
        "egeloen/serializer": "^1.0@dev",
        "egeloen/serializer-bundle": "^1.0@dev",
        "php-http/httplug-bundle": "^1.0",
        "php-http/guzzle6-adapter": "^1.0",
        "bmatzner/jquery-bundle": "~1.12",
        "bmatzner/jquery-ui-bundle": "*",
        "bmatzner/fontawesome-bundle": "~4.6",
        "friendsofsymfony/jsrouting-bundle": "^1.6",
        "jms/serializer-bundle": "^1.1",
        "knplabs/knp-snappy-bundle": "~1.4",
        "wemersonjanuario/wkhtmltopdf-windows": "0.12.2.3",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "symfony/cache": "^3.2"
    },
    "require-dev": {
        "sensio/generator-bundle": "~3.0",
        "symfony/phpunit-bridge": "~2.7"
    },
```
**php --info dump for xml:**

> xml
> 
> XML Support => active
> XML Namespace Support => active
> libxml2 Version => 2.9.4
> 
> xmlreader
> 
> XMLReader => enabled
> 
> xmlwriter
> 
> XMLWriter => enabled

I hope it helps resolving the problem. Thank you, very much !

**Comment by egeloen** [comment] 2017-02-27 18:58
I finally understood what is the root cause of your last problem... :) The issue is the serializer bundle auto discovers metadata mapping files following a pattern in all registered bundles. But... this pattern seems clashing with an other serializers (JMS or Symfony). Basically, the Ivory Serializer tries to load metadata mappings from an other serializer...

**Comment by egeloen** [comment] 2017-02-27 19:57
@ignas3run I just merged the referenced PR. Update the `egeloen/serializer-bundle` and I hope this time everything should work...

**Comment by ignas3run** [comment] 2017-02-28 09:41
Yes! It worked! Thank you a lot!

**Comment by egeloen** [comment] 2017-02-28 10:02
Great, let's close this issue :)

**Closed by egeloen** 2017-02-28 10:02 UTC

**Comment by egeloen** [comment] 2017-02-28 18:37
Btw, I also release the 3.0.0 of the bundle yesterday night :)
