### ISSUE TITLE
Some Problems in Autocomplete

### ISSUE THREAD

**Issue by houssemtayech** [egeloen/IvoryGoogleMapBundle#200] opened 2017-02-13 22:41 UTC
**Autocomplete**:

```
use Ivory\GoogleMapBundle\Form\Type\PlaceAutocompleteType;

$builder->add('field', PlaceAutocompleteType::class);
```
first of all, there is not "PlaceAutocompleteType", it's PlacesAutocompleteType with "S" (PlaceS).

Also for **variable**
```
use Ivory\GoogleMapBundle\Form\Type\PlaceAutocompleteType;

$builder->add('field', PlaceAutocompleteType::class, [
    'variable' => 'place_autocomplete',
]);
```
it generate this problem:

> The option "variable" does not exist. Defined options are: "action", "allow_extra_fields", "async", "attr", "auto_initialize", "block_name", "bound", "by_reference", "cascade_validation", "component_restrictions", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_provider", "csrf_token_id", ...

Configure **Country**
```
use Ivory\GoogleMap\Place\AutocompleteType;
use Ivory\GoogleMapBundle\Form\Type\PlaceAutocompleteType;

$builder->add('field', PlaceAutocompleteType::class, [
    AutocompleteComponentType::COUNTRY => 'fr'
]);
```

>  Ivory\GoogleMap\Place\AutocompleteType

doesn't exist but there are  

> Ivory\GoogleMap\Places\AutocompleteType

with "S" (PlaceS), however  AutocompleteComponentType::COUNTRY  doesn't work

**Comment by egeloen** [comment] 2017-02-14 09:19
@houssemtayech Thanks for your report but unfortunatelly, there is nothing to fix. Let make a long story short, the online doc is the 3.x one (not yet release but I will in the next weeks) whereas it seems you rely on the 2.x code.

**Comment by houssemtayech** [comment] 2017-02-14 15:43
That's cool I'm waiting :)

**Comment by egeloen** [comment] 2017-02-14 19:52
Closing as everything is working fine and it is a duplicate of #197

**Closed by egeloen** 2017-02-14 19:52 UTC
